name: Notify expiry of deploy keys

# This workflow is triggered on pushes to the repository.
on:
  push:
  schedule:
    
    - cron:  '0 6 */1 * *'

jobs:
  notify-of-expiry:
      # This job runs on Linux
    runs-on: ubuntu-latest

    steps:
      # GitHub repository checkout
      - name: GitHub repository checkout
        uses: actions/checkout@v1

      - name: Run python
        run: |
          chmod 700 $GITHUB_WORKSPACE/src/notify_expiry.py
          $GITHUB_WORKSPACE/src/notify_expiry.py ${{ secrets.ORG_ADMIN_PAT_WITH_REPO_SCOPE }}